authors:
  marysueteam:
    name: MarySueTeam
    description: Creator
    avatar: https://github.com/marysueteam.png
  magictooooools:
    name: MagicTooooools
    description: Creator
    avatar: https://github.com/magictooooools.png
  khora:
    name: Khora
    description: Creator
    avatar: https://github.com/allinu.png
